### ISSUE TITLE
Style inactive users

### ISSUE THREAD

**Issue by chris34** [inyokaproject/theme-default#123]
some possible stylings
- grey text-color
- line-through

f.e. via a global css-class?

**Comment by MAH1987** [comment]
like .inactive-user or user-inactive?
how about the del-tag? It has a basicstyle in BS.
http://getbootstrap.com/css/#deleted-text

**Comment by chris34** [comment]
puh, I'm unsure whether `<del>` is supposed for that. I would just use a own css-class; probably `.user-inactive`

**Comment by MAH1987** [comment]
:+1: 
then i would open an PR for this issue and add these class to global css and collect all pages where inactive user are displayed

**Comment by chris34** [comment]
Sounds good. Do have an idea how the HTML-Markup will look like? (spontaneously i would use a small macro, instead of many ifs)

**Comment by MAH1987** [comment]
macro_isUserInactive { user == inactive ? "<span class="user-inactive">USERNAME</span>" : USERNAME } 
or somethind like that :)

**Comment by chris34** [comment]
see #156
