### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by MarkusH** [inyokaproject/theme-default#22]
_From @svijee on September 15, 2014 20:18_

Here is quite unknown, what needs to be done. As a first step:
- [x] Add function to create a wiki page
- [ ] Discuss if there should be a sidebar like in the uu wiki layout, where it is on the right side.
	If there is a sidebar:
	- [ ] Which links should it include
	- [x] Would it be better to have the sidebar on the left side like everywhere else.
- [ ] Investigate what is missing else and define new tasks

Files TODO:
 - [x] action_attach.html 
 - [x] action_attach_edit.html
 - [x] action_backlinks.html
 - [x] action_delete.html
 - [x] action_diff.html
 - [x] action_edit.html
  - [ ] hidden fields?
 - [x] action_log.html
 - [x] ~~action_manage.html~~ all actions are included in the sidebar
 - [x] action_manage_discussion.html
 - [x] action_mv_back.html
 - [x] action_mv_baustelle.html
 - [x] action_mv_discontinued.html
 - [x] action_rename.html
 - [x] action_revert.html
 - [x] action_show.html
 - [x] export.html
 - [x] missing_page.html
 - [x] ~~missing_resource.html~~ not included as more work on the urls will occur

_Copied from original issue: svijee/inyoka#22_

**Comment by chris34** [comment]
basic work is done via #146, #161, #165, #166 . If bugs occur → own issue
