### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by MarkusH** [inyokaproject/theme-default#25]
_From @svijee on September 15, 2014 20:25_
- [x] /calendar/ -- list of upcoming events
- [x] /calendar/2014/10 -- table of events in the specific months
- [x] /calendar/2014/10/11/eventname -- details of an event
  - [x] Add copy-function to sidebar
- [x] ikhaya.ubuntuusers.local:8000/event/1337/edit/ -- edit form of an event
- [x] ikhaya.ubuntuusers.local:8000/event/new/ -- form for adding a new event
- [x] ikhaya.ubuntuusers.local:8000/event/ -- list(table) with events

_Copied from original issue: svijee/inyoka#25_

**Comment by chris34** [comment]
solved via #192
