### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by MarkusH** [inyokaproject/theme-default#28]
_From @svijee on September 15, 2014 20:47_

- [x] fix position of footer
- [ ] set links to license, imprint etc. (configurable?)
- [ ] fix js for sidebar, because of scrolling issues

_Copied from original issue: svijee/inyoka#28_

**Comment by chris34** [comment]
> set links to license, imprint etc. (configurable?)

These pages are generated behind the url `http://<domain>/pages/`. The content and slug are configurable. So i would not include any link in the template, as that will only potential dead links.

**Comment by Lyra2108** [comment]
I don't remind sidebar issues at the moment. And the configurable footer needs changes in the backend and not in the front-end.
So closed for now.

**Comment by chris34** [comment]
Well, _if_ we would like to readd the affix to the sidebar, this would be the right palce imho. Personally, i do not need an affix (also talked a little bit about that with @mah1987), As a) is Voodoo to implement, b) problematic with very long sidebars, which will be heigher than the screen.
