### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by MarkusH** [inyokaproject/theme-default#32]
_From @chris34 on September 19, 2014 20:21_

First the sidebar is some kind of „global“ by using the new macros (see #12, section „Sidebar“). Thus, every time only the macros have to be used. (reconstruction included in issue #14) However, an own less-file does not exist yet. Is it necessary?

Moreover, if wished, the sidebar could be „pushed“ _behind_ the content with `col-md-push-*` or `col-md-pull-*` (see [Bootstrap Docu](http://getbootstrap.com/css/#grid-column-ordering)). At the moment the sidebar is shown _above_ the content. This only affects mobile devices like smartphones.

_Copied from original issue: svijee/inyoka#32_

**Comment by Lyra2108** [comment]
I think we fixed all points in this issue. so it is closed.

**Comment by chris34** [comment]
Well, _if_ we would like to readd the affix to the sidebar, this would be the right palce imho. Personally, i do not need an affix (also talked a little bit about that with @mah1987), As a) is Voodoo to implement, b) problematic with very long sidebars, which will be heigher than the screen.

**Comment by MAH1987** [comment]
No one has the intention to set up an affix

**Comment by Lyra2108** [comment]
So a case of "YAGNI" and done ;)
