### ISSUE TITLE
How do you find the solution of the responsive tables

### ISSUE THREAD

**Issue by MarkusH** [inyokaproject/theme-default#39]
_From @MAH1987 on October 6, 2014 13:40_

In the Modul Planet, is a little Table with all Blogs.
This table is made responsive with :content and data-tags.
Its a fine solution to breaking tables on mobile devices to inline or block Elements.

Is this a solution for all tables in inyoka, or have someone another solution? 

_Copied from original issue: svijee/inyoka#39_

**Comment by Lyra2108** [comment]
It looks like there is no interest in further discussion, so i consider this closed
