### ISSUE TITLE
hide staff-sidebarscection via JS?

### ISSUE THREAD

**Issue by MarkusH** [inyokaproject/theme-default#40]
_From @chris34 on October 7, 2014 19:12_

At the moment you can hide admin-links via JS on uu.de. Should we implement the same function for the new „staff-section“ in the sidebar?

It should be easy to implement, because we generate this secions via a [macro](https://github.com/svijee/inyoka/blob/template_restructure/inyoka/themes/default/templates/macros.html#L19). Thus, we can give them an individual classname and hide DOMs-elements with those classnames.

_Copied from original issue: svijee/inyoka#40_

**Comment by chris34** [comment]
After rethinking this issue, i would not implement it. Basic reason: In the past more users were confused about (accidentally) hidden links. So i will close this issue for now. If someone wants this feature, feel free to reopen it.
