### ISSUE TITLE
add license-notices to files

### ISSUE THREAD

**Issue by MarkusH** [inyokaproject/theme-default#41]
_From @chris34 on October 7, 2014 19:20_

At the beginning of uu.de-templates is always a license-notice. It inidcates that these files are created and licensed under our projects-conditions. (f.e. [ubuntuusers/overall.html](https://github.com/inyokaproject/inyoka/blob/staging/inyoka/templates/overall.html#L1-11) ) However, in the default-templates these notices are ignored or forgotten – they simply do not exist sometimes.

This does not affect only HTML-, it also affects JS- oder LESS-files.

_Copied from original issue: svijee/inyoka#41_

**Comment by Lyra2108** [comment]
Maybe @ostcar can say anythink to the copyright issue in the .js-files? Does it need to have the copy-right from the uu-theme, do we need to check where it initial was copied from,…

**Comment by Lyra2108** [comment]
As disscussed on the TT closed for now
