### ISSUE TITLE
consistent sidebar

### ISSUE THREAD

**Issue by MarkusH** [inyokaproject/theme-default#42]
_From @chris34 on October 7, 2014 19:42_
- generate sidebar via macros
- add placeholder for ikhaya/news and planet → https://github.com/inyokaproject/inyoka/pull/199/files

At least I have a question: How to display sidebar options, if a user is logged out? F.e. for ikhaya-articles atm a link to reports is displayed. (if you click it you have to login, in order to create a report) Instead, the button to be informed about new comments will not be displayed. Why? Because the state (has the user already subscribed to it?) of it is unknown befor login. Is this logical? Or should i better change it, so that no buttons are display until a user is logged in? Or alternativly are always displayed?

I added an TODO, because this affects LESS/stylehseet (which is restructured atm by @Lyra2108)

```
 ./planet/page.html:          {# TODO: swap pencil to the right #}
```

_Copied from original issue: svijee/inyoka/pull/42_

**Comment by Lyra2108** [comment]
@chris34 I think this is outdated. Could you please close it, if this is the case?
