### ISSUE TITLE
Display sidebar options and links, if logged out?

### ISSUE THREAD

**Issue by MarkusH** [inyokaproject/theme-default#43]
_From @chris34 on October 11, 2014 12:4_

As already  discussed shortly in #42, the question is whether to display sidebar options or links, if a user is logged out. If a button is clicked without being logged in, you will be redirected to the login page. (and the action will processed) F.e. in ikhaya-articles a button to report a misspelling or to be informed about new comments exists.

Ideas to solve this so far:

 1. display no options if logged out
 1. display all – or at least some – options that are important
 1. display an icon (lock f.e.) or/and tooltip beneath those links. Thus, the user knows that he has to login in order to use the function.

Personally, I would prefer option 3. So the options are easy to access, however users know that they will have to login.

_Copied from original issue: svijee/inyoka#43_

**Comment by Lyra2108** [comment]
I would prefer option 1. 1st I don't like to be redirected and forced to login. 2nd not all users have an account, so it is also kind of fishing for users.
