### ISSUE TITLE
add menu item for pastebin

### ISSUE THREAD

**Issue by MarkusH** [inyokaproject/theme-default#58]
_From @chris34 on November 4, 2014 0:40_

Just a little idea to include a small icon (instead of full text in desktop) for the paste-app. Otherwise we have to link to the app on the portal page (f.e. in the sidebar).

_Copied from original issue: svijee/inyoka/pull/58_

**Comment by Lyra2108** [comment]
@chris34 Could you take a look at this again? If i remember it correct we also had a discussion in IRC about this.

Do you still want to add it in the header, or is a link on the portal page fine for you?

**Comment by chris34** [comment]
As it is now in the portal-sidebar, i will close this (for now).
