### ISSUE TITLE
macro imports: as macros vs. import xy (or *)

### ISSUE THREAD

**Issue by chris34** [inyokaproject/theme-default#96]
Problem: The are 2 types for importing macros and atm they are not used consequent.

The first is

```
import macros.html as macros
```

The alternative is

```
from macros import input, outer_form
```

or even more general

```
from macros.html import *
```

Personally, I like the first technique more. Why?
1. as macros are imported in base.html, they are automatically available in the extended templates. So we do not have to import it 100 of times. (just my feeling?)
2. in order to use it, we have to use the prefix `macros.`. So it is clear if it is a "global" macro.

As almost everything should extend from base.html, it should be easy to change. Are they any arguments against it?

**Comment by MarkusH** [comment]
- I'm -1 on the first as this clutters the template context.
- I'm +1 on the second because it is exactly the Python syntax.
- I'm -0 on the third, since star imports clutter the context as well, though this is also Python syntax

**Comment by chris34** [comment]
> I'm +1 on the second because it is exactly the Python syntax.

well, Jinjas `extends` will clutter here, too. For instance, i import the macro `breadcrumb_item` in 'base.html' via

```
{% from 'macros.html' import breadcrumb_item %}
```

Fine, i can make a breadcrumb item inside of 'base.html'. However, its possible to use 'breadcrumb_item' in f.e. 'user_edit_privileges.html', too  – without importing it there a second time. Why? imho because 'user_edit_privileges.html' extends 'portal/user_admin.html' which extends 'portal/base.html' which finally extends 'base.html'.  If you remove the extends and `super()` in the blocks inside of 'user_edit_privileges.html', the dev-servers says:

```
UndefinedError: 'breadcrumb_item' is undefined
```

Thats the reason why i would prefer to import marcos once in base.html and use it with the prefix `macros.` everywhere.

**Comment by Lyra2108** [comment]
I would prefer the first variant, because you don't have to write always the same long list of imports, but it's still easy to see were the function comes from.
And i am against the third, because you only will have troubles with your namespace.
